### ISSUE TITLE
Way to calculate the offset dynamically?

### ISSUE THREAD

**Issue by Jupiops** [intellisec/devolo#1]
As the title says: is there a way to calculate the offset dynamically?

I would like to extract the firmware for the 'dLAN 1200+ WiFi ac' which you can find here
http://fwupdate.devolo.com/autoupdate/update1/
in the directory MT2673

The firmware for the 'dLAN 550 WiFi' can be found in the directory MT2734

**Comment by intellisec** [comment]
I assume you mean the offsets in `dvl_builder/dvl_keys.py`, right?
I guess it would be possible, but we haven't looked into it. Also we have only looked at the 550 model in detail.

We would be extremely happy, though, if you dig into this and issue a pull request :heart:
